; generated by Slic3r 1.2.9 on 2016-11-21 at 21:45:25

; external perimeters extrusion width = 0.30mm
; perimeters extrusion width = 0.31mm
; infill extrusion width = 0.31mm
; solid infill extrusion width = 0.31mm
; top infill extrusion width = 0.31mm
; support material extrusion width = 0.30mm

G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

M104 S0; extruder temp off
M190 S30 ; wait for bed temperature 30
M104 S190 ; set temperature
M190 S55 ; wait for bed temperature 55
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S190 ; wait for temperature to be reached

G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G1 X-10 Y0 Z0.1 ; Goto bottom left position (left of bed)

M84     ; disable motors
M70 P60000 Calibrating Z for 0.1 mm
